### ISSUE TITLE
opencc 1.0.x support

### ISSUE THREAD

**Issue by lichray** [buganini/bsdconv-opencc#1]
It's not fully API compatible to the the 0.4.x series.  We need to resolve this issue ASAP to unblock opencc (and related ports) upgrades on FreeBSD.

**Comment by buganini** [comment]
work in progress...

**Comment by buganini** [comment]
fixed in 3bb41f38671992ff21c8579b702876188a4c7b4c

**Comment by iblislin** [comment]
freebsd ports patch is here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210840
